# Generated by Django 5.1.6 on 2025-03-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GelirKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gelir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelir', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gelir_aciklama', models.CharField(blank=True, max_length=150, null=True)),
                ('tarih', models.DateField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gelirler', to='Muhasebe.gelirkategori')),
            ],
        ),
    ]
