# Generated by Django 5.1.6 on 2025-03-18 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muhasebe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gider_Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gider_tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gider_aciklama', models.CharField(blank=True, max_length=150, null=True)),
                ('tarih', models.DateField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giderler', to='Muhasebe.gelirkategori')),
            ],
        ),
    ]
