# Generated by Django 5.1.6 on 2025-03-18 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muhasebe', '0002_gider_kategori_gider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura_Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fatura_Bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateField(auto_now=True)),
                ('tarih_son_ödeme', models.DateField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatura_bilgileri', to='Muhasebe.gelirkategori')),
            ],
        ),
    ]
