# Generated by Django 5.1.6 on 2025-03-18 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muhasebe', '0003_fatura_kategori_fatura_bilgileri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura_bilgileri',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatura_bilgileri', to='Muhasebe.fatura_kategori'),
        ),
    ]
