# Generated by Django 5.1.6 on 2025-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muhasebe', '0005_musteriler'),
    ]

    operations = [
        migrations.AddField(
            model_name='gider',
            name='gider_durum',
            field=models.BooleanField(default=False),
        ),
    ]
