# Generated by Django 5.1.6 on 2025-03-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muhasebe', '0006_gider_gider_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura_bilgileri',
            name='durum',
            field=models.BooleanField(default=False),
        ),
    ]
