# Generated by Django 5.1.6 on 2025-03-19 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muhasebe', '0007_fatura_bilgileri_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteriler',
            name='eklenme_tarihi',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
