# Generated by Django 5.1.6 on 2025-03-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muhasebe', '0008_musteriler_eklenme_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gider',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giderler', to='Muhasebe.gider_kategori'),
        ),
    ]
