# Generated by Django 5.1.6 on 2025-03-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muhasebe', '0009_alter_gider_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelir',
            name='Durum',
            field=models.BooleanField(default=True),
        ),
    ]
